import Navbar from './components/navbar/Navbar'
import Footer from './components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './redux/provider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Halal Mart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${inter.className} `}>
          <Navbar />
          <ToastContainer
            theme="light"
            position="top-right"
            autoClose={3000}
            closeOnClick
            pauseOnHover
          />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  )
}
